Seeds
mferreri7/apparki pull request #2
Opened 2018-06-15 21:20 UTC by dlopezg3

2018-06-15 22:00 UTC, mferrerisaza requested changes

2018-06-15 22:00 UTC, mferreri7 commented on db/seeds.rb
> +  password: "123456",
Estás seguro que esto no falla sin el password_confirmation?

2018-06-15 22:06 UTC, mferrerisaza requested changes

2018-06-15 22:06 UTC, mferreri7 commented on config/routes.rb
> +  get 'tickets/index'
Estás rutas son para que?
Con las de abajo no tenemos?

2018-06-15 22:06 UTC, mferreri7 commented on config/routes.rb
> +  resources :tickets, only: [:new, :show, :create, :index, :edit, :update]
Acá podés user except:
resources :tickets, except: [:delete]

2018-06-15 22:06 UTC, mferreri7 commented on config/routes.rb
> +  resources :vehicles, only: [:new, :create, :index, :show]
Creo que no necesitamos routes de vehicles...Cuando podás lo miramos

2018-06-16 03:49 UTC, dlopezg3 commented on db/seeds.rb
> +  password: "123456",
No es necesario hasta donde entiendo

2018-06-16 03:50 UTC, dlopezg3 commented on config/routes.rb
> +  get 'tickets/index'
Esas estaban desde que cogí el código y desps no las borre, borradas

2018-06-16 03:50 UTC, dlopezg3 commented on config/routes.rb
> +  resources :tickets, only: [:new, :show, :create, :index, :edit, :update]
done

2018-06-16 03:50 UTC, dlopezg3 commented on config/routes.rb
> +  resources :vehicles, only: [:new, :create, :index, :show]
queda pendiente

2018-06-16 03:58 UTC, mferreri7 commented
Todo en orden pero tenés conflicts

2018-06-16 04:05 UTC, dlopezg3 commented
Iba a hacer el push solo de los cambios pero se me subio todo lo que había hecho entonces obvio quedó lleno de conflicts.

Pense que se me había borrado todo. Me salvó que hice ese push

2018-06-16 04:32 UTC, closed without merging