Ticket index backend
mferreri7/apparki pull request #4
Opened 2018-06-16 04:30 UTC by dlopezg3

Me enrede parce me enrede. El core del code quedo en conflics revuelto con lo tuyo.  Era la forma fácil de no perder el trabajo.

2018-06-16 15:22 UTC, mferrerisaza requested changes
Mk lo veo melo, solo mirá lo que te puse ahí de la distancia de tiempo y me decís si lo dejamos así o lo cambias!

Abrazo fraterno!
HBD!

2018-06-16 15:22 UTC, mferrerisaza commented on app/helpers/application_helper.rb
> +  def parking_time(entry)
Esto creo que lo podemos refactorizar bastante 
Pillá:

[Esto que trae rails](http://api.rubyonrails.org/v5.2.0/classes/ActionView/Helpers/DateHelper.html#method-i-distance_of_time_in_words
)+
[Y esto para traducirlo](https://gist.github.com/vicvans20/bdc81e84f9deb3616cbe8bacbe4cba76)

2018-06-16 15:22 UTC, mferrerisaza commented on config/routes.rb
> +  root to: 'pages#home'
Y borrate esto porfa! yo lo había borrado pero demás que en el merge volvió a quedar ahí

2018-06-17 00:30 UTC, dlopezg3 commented on app/helpers/application_helper.rb
> +  def parking_time(entry)
Mk ahí lo estuve revisando y preferí dejarlo como lo tenemos pq es más flexible y nos da más opciones.  El otro es para cositas más estandar.  Aparte la traducción me pudo  jeje

2018-06-17 02:34 UTC, merged